#!/usr/bin/env node
// llm-to-dirs.mjs — Convert LLM-generated scenario JSON array into scenarios-v5/<id>/ dirs.
// Usage: node llm-to-dirs.mjs <input.json>

import fs from 'node:fs';
import path from 'node:path';

const [, , inputPath] = process.argv;
if (!inputPath) { console.error('usage: llm-to-dirs.mjs <input.json>'); process.exit(2); }

const raw = fs.readFileSync(inputPath, 'utf8');
let scenarios;

// Try multiple parse strategies (LLMs often produce slightly malformed JSON)
function tryParseArray(text) {
  try { return JSON.parse(text); } catch {}
  // Extract fenced ```json block
  const m = text.match(/```json\s*([\s\S]*?)```/);
  if (m) {
    try { return JSON.parse(m[1]); } catch {}
  }
  // Try each scenario object individually (split on },{ at top level)
  const arrMatch = text.match(/\[([\s\S]*)\]/);
  const inner = arrMatch ? arrMatch[1] : text;
  const objects = [];
  let depth = 0, start = -1, inStr = false, escNext = false;
  for (let i = 0; i < inner.length; i++) {
    const c = inner[i];
    if (escNext) { escNext = false; continue; }
    if (c === '\\') { escNext = true; continue; }
    if (c === '"') { inStr = !inStr; continue; }
    if (inStr) continue;
    if (c === '{') { if (depth === 0) start = i; depth++; }
    else if (c === '}') { depth--; if (depth === 0 && start !== -1) { objects.push(inner.slice(start, i + 1)); start = -1; } }
  }
  const parsed = [];
  for (const o of objects) {
    try { parsed.push(JSON.parse(o)); } catch (e) { console.warn(`SKIP malformed scenario object (length ${o.length}): ${e.message.slice(0, 80)}`); }
  }
  return parsed;
}

scenarios = tryParseArray(raw);
if (!Array.isArray(scenarios)) throw new Error('Failed to parse as JSON array');
if (scenarios.length === 0) { console.error('No scenarios parsed'); process.exit(1); }
console.log(`Parsed ${scenarios.length} scenarios from input`);

const here = path.dirname(new URL(import.meta.url).pathname);
let created = 0, skipped = 0;
for (const s of scenarios) {
  if (!s.id || !s.prompt_alpha || !s.prompt_beta || !s.oracle_criteria) {
    console.warn(`SKIP ${s.id || '?'}: missing required fields`);
    skipped++; continue;
  }
  const dir = path.join(here, s.id);
  if (fs.existsSync(dir)) { console.warn(`SKIP ${s.id}: exists`); skipped++; continue; }
  fs.mkdirSync(path.join(dir, 'src'), { recursive: true });

  // meta.json
  fs.writeFileSync(path.join(dir, 'meta.json'), JSON.stringify({
    id: s.id, template: 'LLM',
    category: s.category, hypothesis_target: s.hypothesis_target,
    generated_at: new Date().toISOString(),
    generator: s.id.charAt(1), // A / B / G
  }, null, 2));

  // src files
  for (const f of (s.src_files || [])) {
    fs.writeFileSync(path.join(dir, 'src', f.name), f.content);
  }

  // prompts
  fs.writeFileSync(path.join(dir, 'PROMPT.alpha.md'), s.prompt_alpha);
  fs.writeFileSync(path.join(dir, 'PROMPT.beta.md'), s.prompt_beta);

  // ORACLE
  fs.writeFileSync(path.join(dir, 'ORACLE.json'), JSON.stringify({
    scenario: s.id, notes: `LLM-generated by ${s.id.charAt(1)} arm — ${s.category}`,
    criteria: s.oracle_criteria,
  }, null, 2));

  console.log(`✓ ${s.id} (${s.category})`);
  created++;
}
console.log(`\nCreated ${created}, skipped ${skipped}`);
